title: "Best Solar Installers Near Me"
description: "Find the best solar companies . We rank solar installers based on consumer reviews, and show data on local solar costs and available incentives."
email: mrgabonijeff@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: John
paginate: 8
disqus: "demowebsite"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

ganalytics:
# Authors
authors:
  Ruby:
    name: John
    display_name: John

# Social
social:
  facebook: https://www.facebook.com/solarinstallernearme

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-loading-lazy

url: "https://solarinstaller.me" # the base hostname & protocol for your site
exclude :
 - admin
