title: "Best Solar Installers Near Me"
description: "Find the best solar companies . We rank solar installers based on consumer reviews, and show data on local solar costs and available incentives."
email: mrgabonijeff@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: killcreek
paginate: 8
disqus: "demowebsite"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

ganalytics:
# Authors
authors:
  Ruby:
    name: John
    display_name: John

# Social
social:
  facebook: https://www.facebook.com/solarinstallernearme

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-loading-lazy
  - jekyll-compress-images

url: "https://solarinstallerme.github.io" # the base hostname & protocol for your site

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  pngout: false
  svgo: false
  verbose: false

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

exclude:
  - _compress_images_cache.yml

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################

future: false